<?php

namespace DoctrineProxies\__CG__\App\Models\Websocket;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WebSocketConnection extends \App\Models\Websocket\WebSocketConnection implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'id', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'user', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'admin', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'clientId', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'channel', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'timeZone', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'active', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'createdDateTime', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'updatedDateTime'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'id', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'user', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'admin', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'clientId', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'channel', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'timeZone', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'active', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'createdDateTime', '' . "\0" . 'App\\Models\\Websocket\\WebSocketConnection' . "\0" . 'updatedDateTime'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WebSocketConnection $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function deactivate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deactivate', []);

        return parent::deactivate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Models\User\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin(): ?\App\Models\Admin\Admin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin', []);

        return parent::getAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function getClientId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientId', []);

        return parent::getClientId();
    }

    /**
     * {@inheritDoc}
     */
    public function getChannel(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannel', []);

        return parent::getChannel();
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeZone(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeZone', []);

        return parent::getTimeZone();
    }

    /**
     * {@inheritDoc}
     */
    public function isActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDateTime(): \DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDateTime', []);

        return parent::getCreatedDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedDateTime(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedDateTime', []);

        return parent::getUpdatedDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Models\User\User $user): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin(?\App\Models\Admin\Admin $admin): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin', [$admin]);

        parent::setAdmin($admin);
    }

    /**
     * {@inheritDoc}
     */
    public function setClientId(string $clientId): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientId', [$clientId]);

        parent::setClientId($clientId);
    }

    /**
     * {@inheritDoc}
     */
    public function setChannel(string $channel): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChannel', [$channel]);

        parent::setChannel($channel);
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeZone(string $timeZone): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeZone', [$timeZone]);

        parent::setTimeZone($timeZone);
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(bool $active): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDateTime(\DateTimeImmutable $createdDateTime): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDateTime', [$createdDateTime]);

        parent::setCreatedDateTime($createdDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedDateTime(?\DateTimeImmutable $updatedDateTime): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedDateTime', [$updatedDateTime]);

        parent::setUpdatedDateTime($updatedDateTime);
    }

}
